// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProgramsController from "./programs_controller"
application.register("programs", ProgramsController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SearchExerciseController from "./search_exercise_controller"
application.register("search-exercise", SearchExerciseController)

import UtilsController from "./utils_controller"
application.register("utils", UtilsController)
