require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/routine_exercises", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RoutineExercise. As you add validations to RoutineExercise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RoutineExercise.create! valid_attributes
      get routine_exercises_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      routine_exercise = RoutineExercise.create! valid_attributes
      get routine_exercise_url(routine_exercise)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_routine_exercise_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      routine_exercise = RoutineExercise.create! valid_attributes
      get edit_routine_exercise_url(routine_exercise)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RoutineExercise" do
        expect {
          post routine_exercises_url, params: { routine_exercise: valid_attributes }
        }.to change(RoutineExercise, :count).by(1)
      end

      it "redirects to the created routine_exercise" do
        post routine_exercises_url, params: { routine_exercise: valid_attributes }
        expect(response).to redirect_to(routine_exercise_url(RoutineExercise.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RoutineExercise" do
        expect {
          post routine_exercises_url, params: { routine_exercise: invalid_attributes }
        }.to change(RoutineExercise, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post routine_exercises_url, params: { routine_exercise: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested routine_exercise" do
        routine_exercise = RoutineExercise.create! valid_attributes
        patch routine_exercise_url(routine_exercise), params: { routine_exercise: new_attributes }
        routine_exercise.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the routine_exercise" do
        routine_exercise = RoutineExercise.create! valid_attributes
        patch routine_exercise_url(routine_exercise), params: { routine_exercise: new_attributes }
        routine_exercise.reload
        expect(response).to redirect_to(routine_exercise_url(routine_exercise))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        routine_exercise = RoutineExercise.create! valid_attributes
        patch routine_exercise_url(routine_exercise), params: { routine_exercise: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested routine_exercise" do
      routine_exercise = RoutineExercise.create! valid_attributes
      expect {
        delete routine_exercise_url(routine_exercise)
      }.to change(RoutineExercise, :count).by(-1)
    end

    it "redirects to the routine_exercises list" do
      routine_exercise = RoutineExercise.create! valid_attributes
      delete routine_exercise_url(routine_exercise)
      expect(response).to redirect_to(routine_exercises_url)
    end
  end
end
